### ISSUE TITLE
Mouse Wheel not Working

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#57]
Mouse wheel (up/down) stopped working in new 0.5.3 version.

Log: 

```
File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 824, in wheel
    Mouse().wheel(direction, steps)
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 1225, in wheel
    return PlatformManager.mouseWheel(direction, steps)
  File "C:\Python27\lib\site-packages\lackey\PlatformManagerWindows.py", line 342, in mouseWheel
    mouse._os_mouse.queue.put(WheelEvent(wheel_moved, time.time()))
AttributeError: 'module' object has no attribute 'queue'
```

**Comment by glitchassassin** [comment]
Changes in the `keyboard` module seem to have affected this piece. Submitting a pull request to fix its mouse wheel functionality.

**Comment by glitchassassin** [comment]
The pull request has been implemented and mouse wheel functionality has been added to `keyboard`. I've updated the InputEmulation piece to reflect this.

**Comment by glitchassassin** [comment]
This has been rolled out with the latest release.

**Comment by maxdule** [comment]
This still doesn't seem to be working in 0.5.4 version.   


```
scr.wheel(loc, 1, n)
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 825, in wheel
    self.mouseMove(PSRML)
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 822, in mouseMove
    Mouse().moveSpeed(PSRML)
  File "C:\Python27\lib\site-packages\lackey\InputEmulation.py", line 49, in moveSpeed
    if mouse.get_position() == original_location and original_location != location.getTuple():
AttributeError: 'Match' object has no attribute 'getTuple'
```

**Comment by glitchassassin** [comment]
That's what I get for not doing enough testing.

I've pushed a fix to the develop ring, and added a basic sanity check in my regular tests. Apologies for taking a while to get to this, I've been busy lately.

**Comment by glitchassassin** [comment]
This has (finally) been rolled out to the master ring and published to Pypi. Sorry again for taking so long.
